# Site settings
title: Blog de Viajes
email: viajesblog@gmail.com
description: Un blog divertido sobre viajar.
baseurl: "/blog-de-viajes"
twitter_username: anti_tk 
avatar: "http://as00.epimg.net/img/comunes/fotos/fichas/equipos/large/4175.png" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Manuel Gutierrez" # Set default author name
      categories: "lugares"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
